'use strict';

const test = require('node:test');
const assert = require('node:assert');

const { fingerprint } = require('../lib/fingerprint');
const { createViolation } = require('../lib/violation');
const diffEngine = require('../lib/diff-engine');

// The `fingerprintKey` escape hatch, and — far more importantly — the guarantee
// that adding it did not disturb the identity of any violation that does NOT use
// it. Every baseline in every repo is a map keyed by these hashes. If the default
// scheme ever shifts by one byte, every baselined violation on earth reads as new
// the moment its owner upgrades, and the tool blocks every commit in the repo it
// was installed to unblock.

test.describe('default identity is frozen (v2.5.2 compatibility)', () => {
  // These digests were computed with the v2.5.2 implementation, BEFORE
  // fingerprintKey existed, and pasted here as literals.
  //
  // They are deliberately NOT generated by calling the current code — a test that
  // computes its own expectation cannot fail, it can only agree with whatever the
  // implementation currently does. Hardcoding is the entire point: these are a
  // fossil of the old behavior, and the new code must still match the fossil.
  const FROZEN = [
    {
      v: { file: 'src/a.js', ruleId: 'no-unused-vars', message: "'x' is assigned a value but never used." },
      sha1: '86eadaa25c3c6d7c5f788f9e8039e876b0e734d0',
    },
    {
      v: { file: 'src/a.js', ruleId: 'no-unused-vars', message: "'y' is assigned a value but never used." },
      sha1: '93701c74db2884bec545096559bef2dc46c24a99',
    },
    {
      // Windows path — normalization must still collapse to forward slashes.
      v: { file: 'src\\win\\b.ts', ruleId: 'no-explicit-any', message: 'Unexpected any.' },
      sha1: '072b69da61483545c225ecb9de2a52408ad0ec8b',
    },
    {
      // Internal whitespace run — message normalization must still collapse it.
      v: { file: 'app/main.py', ruleId: 'E501', message: 'Line too long   (100 > 88)' },
      sha1: 'ce07de96a1535fa246f321b4ae5c56588a66ae49',
    },
    {
      v: { file: 'main.go', ruleId: 'errcheck', message: 'Error return value is not checked' },
      sha1: '95e7fbb3c452fe99915125478dfd4864b3040e58',
    },
    {
      // Degenerate: empty file, null rule. Must still hash the way it used to.
      v: { file: '', ruleId: null, message: null },
      sha1: '5bdb03f00d4c079e4b3b429a39288401aad77129',
    },
    {
      v: {
        file: 'x.tf',
        ruleId: 'terraform_required_version',
        message: 'terraform "required_version" attribute is required',
      },
      sha1: 'a3c199d4d45cbab4d62fefee3948bb1645d452ba',
    },
  ];

  for (const { v, sha1 } of FROZEN) {
    test(`raw object: ${v.file || '<empty>'} / ${v.ruleId} is unchanged`, () => {
      assert.strictEqual(fingerprint(v), sha1);
    });

    test(`via createViolation: ${v.file || '<empty>'} / ${v.ruleId} is unchanged`, () => {
      // createViolation now sets `fingerprintKey: null`. Prove that the added
      // field does not leak into the hash of a violation that never set it.
      assert.strictEqual(fingerprint(createViolation(v)), sha1);
    });
  }

  test('an explicitly null/empty key falls back to the default scheme', () => {
    const base = { file: 'src/a.js', ruleId: 'no-unused-vars', message: "'x' is assigned a value but never used." };
    const expected = '86eadaa25c3c6d7c5f788f9e8039e876b0e734d0';
    assert.strictEqual(fingerprint({ ...base, fingerprintKey: null }), expected);
    assert.strictEqual(fingerprint({ ...base, fingerprintKey: '' }), expected);
    assert.strictEqual(fingerprint({ ...base, fingerprintKey: undefined }), expected);
  });
});

test.describe('keyed identity', () => {
  test('the key replaces file and message entirely', () => {
    const a = createViolation({
      file: 'app/schemas/deal.py',
      ruleId: 'contract/column-not-writable',
      message: 'no write schema accepts [operating_expenses]',
      fingerprintKey: 'Deal.operating_expenses:writable',
    });
    // Same subject, but the schema moved to a new file AND the message got
    // reworded (the enumerated set changed). This is the whole reason the key
    // exists: neither of those is a different problem.
    const b = createViolation({
      file: 'app/api/v2/schemas/deal.py',
      ruleId: 'contract/column-not-writable',
      message: 'no write schema accepts [operating_expenses, taxes, insurance]',
      fingerprintKey: 'Deal.operating_expenses:writable',
    });

    assert.strictEqual(fingerprint(a), fingerprint(b));
  });

  test('a different key is a different violation', () => {
    const mk = (key) =>
      createViolation({ ruleId: 'contract/column-not-writable', fingerprintKey: key });
    assert.notStrictEqual(
      fingerprint(mk('Deal.operating_expenses:writable')),
      fingerprint(mk('Deal.taxes:writable'))
    );
  });

  test('the same key under a different rule is a different violation', () => {
    const mk = (ruleId) => createViolation({ ruleId, fingerprintKey: 'Deal.taxes' });
    assert.notStrictEqual(
      fingerprint(mk('contract/column-not-writable')),
      fingerprint(mk('contract/column-not-readable'))
    );
  });

  test('a keyed violation cannot collide with a default-scheme one', () => {
    // The schemes hash arrays of different arity, so no crafted file/message can
    // ever produce the digest of a keyed violation.
    const keyed = createViolation({ ruleId: 'r', fingerprintKey: 'X.y' });
    const unkeyed = createViolation({ file: 'X.y', ruleId: 'r', message: '' });
    assert.notStrictEqual(fingerprint(keyed), fingerprint(unkeyed));
  });
});

test.describe('keyed violations survive a file move through the diff engine', () => {
  test('a baselined finding stays baselined after its file is renamed', () => {
    const before = [
      createViolation({
        file: 'app/schemas/deal.py',
        ruleId: 'contract/column-not-writable',
        message: 'no write schema accepts [operating_expenses]',
        fingerprintKey: 'Deal.operating_expenses:writable',
      }),
    ];

    // Baseline it where it lives today.
    const baseline = {};
    for (const v of before) baseline[fingerprint(v)] = 1;

    // Someone reorganizes the package. Same defect, new path.
    const after = [
      createViolation({
        file: 'app/domain/deal/schemas.py',
        ruleId: 'contract/column-not-writable',
        message: 'no write schema accepts [operating_expenses]',
        fingerprintKey: 'Deal.operating_expenses:writable',
      }),
    ];

    const result = diffEngine.diff(after, baseline);
    assert.strictEqual(result.new.length, 0, 'a moved file must not resurrect a baselined finding');
    assert.strictEqual(result.baselined.length, 1);
    assert.strictEqual(result.fixed.length, 0, 'and it must not look "fixed" either');
  });

  test('without a key, the same move DOES look new (the behavior the key exists to fix)', () => {
    const mk = (file) =>
      createViolation({ file, ruleId: 'x/y', message: 'same message' });

    const baseline = { [fingerprint(mk('a/old.py'))]: 1 };
    const result = diffEngine.diff([mk('b/new.py')], baseline);

    // Not a bug — it is the documented limitation of path-based identity, and the
    // reason schema adapters supply a key instead.
    assert.strictEqual(result.new.length, 1);
    assert.strictEqual(result.fixed.length, 1);
  });
});
