'use strict';

const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawnSync } = require('child_process');
const { LinterAdapter, TIER, STAGE } = require('./adapter');
const { createViolation, SEVERITY } = require('../violation');
const configManager = require('../config-manager');

// THE LAST UNGUARDED RUNG.
//
//   Postgres columns
//        ⇕   alembic-check                       guarded
//   SQLAlchemy models
//        ⇕   17 contract rules                   guarded
//   Pydantic schemas
//        ↓   materialize → openapi.json          guarded
//   openapi.json
//        ↓   openapi-typescript → api-types.ts   ← THIS
//   frontend types
//
// Drift lives wherever two artifacts must AGREE. It cannot exist where one is
// DERIVED. Every rung above needed human declarations to resolve — is this absent
// column a bug or a decision? — and those were the hard ones, and they are done.
//
// This rung needs no declarations at all. It is pure derivation. Once the check
// exists, a whole class of bug stops being *tested for* and becomes *impossible to
// express*.
//
// WHAT IT CATCHES, FROM THE WILD
//
// A component read `prospect.zip`. The API returns `zip_code`. The backend was
// correct, the contract check was green, the lockfile was fresh, the database row was
// right — and the user saw a blank ZIP field for a full release cycle, because
// `undefined` renders as nothing, and nothing looks exactly like "the data was never
// saved".
//
// A hand-written `TaskFormData` declared `estimated_hours` (no such column — the real
// one is `estimated_cost`, one word away) and `dependencies` (no such column), while
// omitting `notes`, `deal_id`, `estimated_cost`. Wrong in both directions at once, and
// every check we ship passes it, because the lie is not in Python.
//
// With generated types the first is a compile error and the second is inexpressible.
// Both were found by a human clicking around in a browser. That is not a repeatable
// strategy.

// Generators we know. `command` is the escape hatch for everything else — we are not
// going to abstract over generators we have never seen.
const GENERATORS = {
  'openapi-typescript': {
    bin: 'openapi-typescript',
    args: (lockfile, out) => [lockfile, '-o', out],
    // The generator signs its own work. That signature is what makes it safe to
    // regenerate — and its absence is what makes a file sacred.
    banner: /auto-generated by openapi-typescript/i,
    versionArgs: ['--version'],
  },
};

class CodegenDriftAdapter extends LinterAdapter {
  get id() {
    return 'codegen-drift';
  }

  get languages() {
    return ['javascript', 'typescript'];
  }

  /**
   * No autofix. `materialize` regenerates — deliberately, by a human running a command.
   * A hook that rewrites your types behind your back is a hook that commits code you
   * never read.
   */
  get supportsFix() {
    return false;
  }

  /**
   * ...but it is not a hand-fix either, and that distinction matters to whoever —
   * or whatever — reads the failure. Both rules this adapter emits already name
   * this command in their message; declaring it here is what lets the REPORT say
   * it too, instead of falling back to "fix it by hand" and sending a reader to
   * edit a generated file that `materialize` will overwrite.
   */
  get remediation() {
    return 'gimme-the-lint materialize';
  }

  get tier() {
    return TIER.LOCAL;
  }

  /**
   * COMMIT stage, unlike `contract` and `openapi`.
   *
   * This adapter never imports the application. It reads a committed JSON file and runs
   * a JS generator over it — milliseconds, like spectral. So it can afford to run on
   * every commit, and the feedback is immediate: regenerate the lockfile, and the very
   * next commit tells you the frontend is behind.
   */
  get stage() {
    return STAGE.COMMIT;
  }

  get sourceExtensions() {
    return ['.ts', '.tsx'];
  }

  /** The `contract` block of the user's config. */
  _contractConfig() {
    const cfg = configManager.getConfig(this.projectRoot) || {};
    return cfg.contract || {};
  }

  /** Every configured codegen target. An ARRAY: a monorepo may have several frontends. */
  targets() {
    const cfg = this._contractConfig();
    const list = Array.isArray(cfg.codegen) ? cfg.codegen : [];
    return list
      .filter((t) => t && t.output)
      .map((t) => ({
        generator: t.generator || 'openapi-typescript',
        command: t.command || null,
        output: path.resolve(this.projectRoot, t.output),
        outputRel: t.output,
      }));
  }

  lockfilePath() {
    const cfg = this._contractConfig();
    return path.resolve(this.appRoot, cfg.lockfile || 'openapi.json');
  }

  get binary() {
    const [first] = this.targets();
    const spec = first && GENERATORS[first.generator];
    const bin = (spec && spec.bin) || 'openapi-typescript';
    return this.resolveBinary([
      path.join(this.appRoot, 'node_modules', '.bin', bin),
      path.join(this.projectRoot, 'node_modules', '.bin', bin),
      bin,
    ]);
  }

  versionArgs() {
    return ['--version'];
  }

  /**
   * THREE explicit signals, all required.
   *
   * We will not guess that a repo wants generated types. A lockfile alone is not
   * consent; a JS app alone is not consent. The user names the generator and the output
   * path, or this adapter stays silent.
   */
  detect() {
    const targets = this.targets();
    if (targets.length === 0) return false;
    return fs.existsSync(this.lockfilePath());
  }

  /**
   * The generator's OWN version — not ours.
   *
   * This is the whole determinism story, and it needs no new machinery. `version()`
   * already feeds `tool_version` into the baseline section, and drift.js already reports
   * `type: 'version'` when it moves. So an openapi-typescript bump that reorders a union
   * surfaces as DRIFT — "your baseline is stale, re-baseline" — rather than as a
   * VIOLATION that blocks a push over something nobody did.
   *
   * Get this wrong and the check fails every repo's CI on an unrelated Tuesday, and the
   * first thing any team does then is disable it. Determinism is not cosmetic; it is what
   * makes the guard survivable.
   */
  version() {
    const result = spawnSync(this.binary, ['--version'], {
      cwd: this.projectRoot,
      encoding: 'utf8',
    });
    if (result.error) return 'unknown';
    const match = `${result.stdout || ''}${result.stderr || ''}`.match(/\d+\.\d+\.\d+/);
    return match ? match[0] : 'unknown';
  }

  /** Did the generator write this file? Its own banner is the answer. */
  _isGenerated(file, generator) {
    const spec = GENERATORS[generator];
    if (!spec || !spec.banner) return false;
    try {
      // The banner is at the top; no need to read a 40,000-line types file to find it.
      const head = fs.readFileSync(file, 'utf8').slice(0, 2000);
      return spec.banner.test(head);
    } catch {
      return false;
    }
  }

  /** Run a generator, returning its output text. Throws if it fails. */
  _generate(target, lockfile) {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'gtl-codegen-'));
    const out = path.join(dir, path.basename(target.output));

    let cmd;
    let args;
    if (target.command) {
      // The escape hatch. {lockfile} and {output} are substituted.
      const parts = target.command
        .replace(/\{lockfile\}/g, lockfile)
        .replace(/\{output\}/g, out)
        .split(/\s+/);
      cmd = parts[0];
      args = parts.slice(1);
    } else {
      const spec = GENERATORS[target.generator];
      if (!spec) {
        const err = new Error(
          `codegen-drift: unknown generator "${target.generator}". Known: ` +
            `${Object.keys(GENERATORS).join(', ')}. For anything else, set \`command\`.`
        );
        err.code = 'ADAPTER_SKIPPED';
        throw err;
      }
      cmd = this.binary;
      args = spec.args(lockfile, out);
    }

    const result = spawnSync(cmd, args, {
      cwd: this.projectRoot,
      encoding: 'utf8',
      maxBuffer: 64 * 1024 * 1024,
    });

    if (result.error || result.status !== 0) {
      const err = new Error(
        `codegen-drift: ${target.generator} failed — ` +
          `${(result.stderr || '').trim() || (result.error && result.error.message)}`
      );
      // A generator that is not installed is a skip (loud, never blocking). A generator
      // that ran and BROKE is an error — it means the lockfile it was given is not
      // something it can read, and we want to hear about that.
      err.code = result.error && result.error.code === 'ENOENT' ? 'ADAPTER_SKIPPED' : 'CODEGEN_FAILED';
      throw err;
    }

    if (!fs.existsSync(out)) {
      const err = new Error(
        `codegen-drift: ${target.generator} exited 0 but wrote no file. ` +
          'Refusing to compare against nothing.'
      );
      err.code = 'CODEGEN_FAILED';
      throw err;
    }

    return fs.readFileSync(out, 'utf8');
  }

  /**
   * Compare the committed generated types against what the COMMITTED LOCKFILE implies.
   *
   * Generating from the committed lockfile — rather than re-deriving from the app — is
   * what keeps the chain honest, and the good behavior falls out for free:
   *
   *   lockfile stale, types match it   → codegen is GREEN. Correct: the types faithfully
   *                                      describe the lockfile; the LOCKFILE is what is
   *                                      wrong, and `lockfile-stale` says so.
   *   materialize refreshes lockfile   → now the types disagree → codegen-stale.
   *
   * Sequential, never simultaneous. One root cause, one finding — because reporting two
   * violations for one cause trains people to ignore both.
   */
  lint() {
    const lockfile = this.lockfilePath();
    const violations = [];

    for (const target of this.targets()) {
      // The committed output does not exist yet. Debt: every repo starts here, and a
      // check you must repair your repo to install is a check nobody installs.
      if (!fs.existsSync(target.output)) {
        violations.push(
          createViolation({
            file: target.outputRel,
            ruleId: 'contract/codegen-missing',
            severity: SEVERITY.ERROR,
            message:
              `${target.outputRel} does not exist, but a generator is configured for it. ` +
              'Your frontend is typed by hand against an API it cannot see. Run: ' +
              'gimme-the-lint materialize',
            source: 'codegen-drift',
            fingerprintKey: `${target.outputRel}:codegen-missing`,
          })
        );
        continue;
      }

      const committed = fs.readFileSync(target.output, 'utf8');

      // PROVENANCE. A file the generator did not sign was written by a person. It is
      // their source of truth, not our output, and it is not ours to rewrite — so we
      // report the disagreement and touch nothing.
      //
      // This is what makes the adapter adoptable at all: every codebase that needs this
      // check is, by definition, one that currently hand-maintains its types.
      if (!this._isGenerated(target.output, target.generator)) {
        const generated = this._generate(target, lockfile);
        if (normalize(generated) !== normalize(committed)) {
          violations.push(
            createViolation({
              file: target.outputRel,
              ruleId: 'contract/codegen-stale',
              severity: SEVERITY.ERROR,
              message:
                `${target.outputRel} is hand-written (it carries no generator banner), and ` +
                'it does not match what your API actually serves. Your compiler is ' +
                'currently believing it. Replace it with generated types: ' +
                'gimme-the-lint materialize — the file will NOT be overwritten until you do.',
              source: 'codegen-drift',
              fingerprintKey: `${target.outputRel}:codegen-stale`,
              neverBaseline: true,
            })
          );
        }
        continue;
      }

      const generated = this._generate(target, lockfile);

      if (normalize(generated) !== normalize(committed)) {
        violations.push(
          createViolation({
            file: target.outputRel,
            ruleId: 'contract/codegen-stale',
            severity: SEVERITY.ERROR,
            message:
              `${target.outputRel} no longer matches ${path.basename(lockfile)}. The client ` +
              'types are describing an API you no longer serve, and the compiler believes ' +
              'them — so a field that has been renamed reads as `undefined`, which renders ' +
              'as nothing, which looks exactly like data that was never saved. Run: ' +
              'gimme-the-lint materialize',
            source: 'codegen-drift',
            fingerprintKey: `${target.outputRel}:codegen-stale`,
            // A DEFECT, not debt. A stale generated type is not a gap — it is a lie the
            // compiler is currently believing. Grandfathering it means writing down "we
            // accept that our frontend is typed against an API we do not serve."
            neverBaseline: true,
          })
        );
      }
    }

    return violations;
  }

  /**
   * Regenerate the types. Returns {path, content} — THE ENGINE WRITES.
   *
   * The adapter never touches the filesystem, so there is exactly one code path that can
   * put bytes in a user's tree, and it is reachable only from an explicit `materialize`.
   */
  materialize() {
    const lockfile = this.lockfilePath();
    const targets = this.targets();
    if (targets.length === 0) return null;

    if (!fs.existsSync(lockfile)) {
      const err = new Error(
        `codegen-drift: ${path.relative(this.projectRoot, lockfile)} does not exist yet — ` +
          'nothing to generate from.'
      );
      err.code = 'MATERIALIZE_FAILED';
      throw err;
    }

    // One target per materialize() call; the engine loops. (The base contract returns a
    // single {path, content}, and multiplying it would complicate every other adapter to
    // serve this one.)
    const [target] = targets;

    // Provenance, checked BEFORE generating. Refusing here rather than after means we
    // never even build the bytes that would have overwritten somebody's file.
    if (
      fs.existsSync(target.output) &&
      !this._isGenerated(target.output, target.generator)
    ) {
      return {
        path: target.output,
        skipped:
          `${target.outputRel} was hand-written (no generator banner) — it is your file, ` +
          'not our output, so it will not be overwritten. Delete it when you are ready to ' +
          'generate, and `check` will keep telling you where it disagrees with the API in ' +
          'the meantime.',
      };
    }

    return { path: target.output, content: this._generate(target, lockfile) };
  }

  parse() {
    return []; // lint() is overridden; nothing reaches here
  }
}

/**
 * Trailing-whitespace and line-ending noise must not read as a contract change.
 *
 * A Windows checkout, an editor that strips trailing newlines, a `.gitattributes` that
 * normalizes CRLF — any of these would otherwise report `codegen-stale` on a file that is
 * semantically identical, and a guard that cries wolf on clean code gets switched off,
 * taking its real findings with it.
 */
function normalize(text) {
  return String(text || '')
    .replace(/\r\n/g, '\n')
    .replace(/[ \t]+$/gm, '')
    .trim();
}

module.exports = CodegenDriftAdapter;
module.exports.GENERATORS = GENERATORS;
module.exports.normalize = normalize;
