'use strict';

const fs = require('fs-extra');
const path = require('path');

const TEMPLATES_DIR = path.join(__dirname, '..', 'templates');

async function copyTemplate(templateName, destPath, substitutions = {}) {
  const templatePath = path.join(TEMPLATES_DIR, templateName);

  if (!await fs.pathExists(templatePath)) {
    throw new Error(`Template not found: ${templateName}`);
  }

  let content = await fs.readFile(templatePath, 'utf8');

  for (const [key, value] of Object.entries(substitutions)) {
    content = content.replace(new RegExp(`\\{\\{${key}\\}\\}`, 'g'), value);
  }

  await fs.ensureDir(path.dirname(destPath));
  await fs.writeFile(destPath, content, 'utf8');
}

async function detectProjectType(projectRoot) {
  const hasFrontend = await fs.pathExists(path.join(projectRoot, 'frontend'));
  const hasBackend = await fs.pathExists(path.join(projectRoot, 'backend'));
  const hasSrc = await fs.pathExists(path.join(projectRoot, 'src'));
  const hasApp = await fs.pathExists(path.join(projectRoot, 'app'));
  const hasPackageJson = await fs.pathExists(path.join(projectRoot, 'package.json'));
  const hasPyproject = await fs.pathExists(path.join(projectRoot, 'pyproject.toml'));
  const hasRequirements = await fs.pathExists(path.join(projectRoot, 'requirements.txt'));

  if (hasFrontend && hasBackend) return 'monorepo';
  if (hasFrontend || (hasSrc && hasPackageJson)) return 'frontend';
  if (hasBackend || hasApp || hasPyproject || hasRequirements) return 'backend';
  if (hasPackageJson) return 'frontend';
  return 'unknown';
}

function getConfig(projectRoot) {
  const configPath = path.join(projectRoot, 'gimme-the-lint.config.js');
  const defaults = {
    frontendDir: 'frontend',
    backendDir: 'backend',
    srcDir: 'src',
    appDir: 'app',
    lttfDir: '.lttf',
    ruffBaselineDir: '.lttf-ruff',
    excludePatterns: [],
    testExcludedFrontend: ['__tests__', 'testing', 'e2e', '*.test.*', '*.spec.*'],
    testExcludedBackend: ['tests', '*test*', '__pycache__'],
  };

  if (fs.existsSync(configPath)) {
    try {
      const userConfig = require(configPath);
      return { ...defaults, ...userConfig };
    } catch {
      return defaults;
    }
  }

  return defaults;
}

async function initConfig(projectRoot, options = {}) {
  const configPath = path.join(projectRoot, 'gimme-the-lint.config.js');

  if (await fs.pathExists(configPath) && !options.force) {
    return { created: false, path: configPath };
  }

  const projectType = await detectProjectType(projectRoot);
  const config = {
    projectType,
    frontendDir: options.frontendDir || 'frontend',
    backendDir: options.backendDir || 'backend',
    srcDir: options.srcDir || 'src',
    appDir: options.appDir || 'app',
  };

  const content = `// gimme-the-lint configuration
// Generated by gimme-the-lint init
module.exports = ${JSON.stringify(config, null, 2)};
`;

  await fs.writeFile(configPath, content, 'utf8');
  return { created: true, path: configPath, projectType };
}

module.exports = {
  copyTemplate,
  detectProjectType,
  getConfig,
  initConfig,
  TEMPLATES_DIR,
};
