'use strict';

const fs = require('fs-extra');
const path = require('path');

const TEMPLATES_DIR = path.join(__dirname, '..', 'templates');

async function copyTemplate(templateName, destPath, substitutions = {}) {
  const templatePath = path.join(TEMPLATES_DIR, templateName);

  if (!await fs.pathExists(templatePath)) {
    throw new Error(`Template not found: ${templateName}`);
  }

  let content = await fs.readFile(templatePath, 'utf8');

  for (const [key, value] of Object.entries(substitutions)) {
    content = content.replace(new RegExp(`\\{\\{${key}\\}\\}`, 'g'), value);
  }

  await fs.ensureDir(path.dirname(destPath));
  await fs.writeFile(destPath, content, 'utf8');
}

async function detectProjectType(projectRoot) {
  const hasFrontend = await fs.pathExists(path.join(projectRoot, 'frontend'));
  const hasBackend = await fs.pathExists(path.join(projectRoot, 'backend'));
  const hasSrc = await fs.pathExists(path.join(projectRoot, 'src'));
  const hasApp = await fs.pathExists(path.join(projectRoot, 'app'));
  const hasPackageJson = await fs.pathExists(path.join(projectRoot, 'package.json'));
  const hasPyproject = await fs.pathExists(path.join(projectRoot, 'pyproject.toml'));
  const hasRequirements = await fs.pathExists(path.join(projectRoot, 'requirements.txt'));

  if (hasFrontend && hasBackend) return 'monorepo';
  if (hasFrontend || (hasSrc && hasPackageJson)) return 'frontend';
  if (hasBackend || hasApp || hasPyproject || hasRequirements) return 'backend';
  if (hasPackageJson) return 'frontend';
  return 'unknown';
}

// Config-file lookup order. The .gtl/ location is canonical — the config
// travels with the committed .gtl/ baselines and keeps gimme-the-lint's own
// files in one place. The repo-root location is retained as a fallback so
// projects created before this layout keep working with no change.
const CONFIG_CANDIDATES = [
  ['.gtl', 'config.cjs'],
  ['.gtl', 'config.js'],
  ['gimme-the-lint.config.cjs'],
  ['gimme-the-lint.config.js'],
];

/** Absolute path of the project's gimme-the-lint config, or null if none. */
function findConfig(projectRoot) {
  for (const parts of CONFIG_CANDIDATES) {
    const candidate = path.join(projectRoot, ...parts);
    if (fs.existsSync(candidate)) return candidate;
  }
  return null;
}

/** Is the target project ESM ("type": "module" in package.json)? */
async function isESMProject(projectRoot) {
  const pkgPath = path.join(projectRoot, 'package.json');
  if (await fs.pathExists(pkgPath)) {
    try {
      return JSON.parse(await fs.readFile(pkgPath, 'utf8')).type === 'module';
    } catch {
      /* unreadable package.json — treat as CommonJS */
    }
  }
  return false;
}

/**
 * Where a NEW config is written — the canonical .gtl/ location. ESM projects
 * get a .cjs extension so `require()` of the CommonJS config still works.
 */
async function newConfigPath(projectRoot) {
  const esm = await isESMProject(projectRoot);
  return path.join(projectRoot, '.gtl', esm ? 'config.cjs' : 'config.js');
}

function getConfig(projectRoot) {
  const defaults = {
    frontendDir: 'frontend',
    backendDir: 'backend',
    srcDir: 'src',
    appDir: 'app',
    skipPatterns: [],
    excludePatterns: [],
    testExcludedFrontend: ['__tests__', 'testing', 'e2e', '*.test.*', '*.spec.*'],
    testExcludedBackend: ['tests', '*test*', '__pycache__'],
  };

  const configPath = findConfig(projectRoot);
  if (configPath) {
    try {
      const userConfig = require(configPath);
      return { ...defaults, ...userConfig };
    } catch {
      return defaults;
    }
  }

  return defaults;
}

async function initConfig(projectRoot, options = {}) {
  const existing = findConfig(projectRoot);

  // Don't overwrite an existing config (wherever it lives).
  if (!options.force && existing) {
    return { created: false, path: existing };
  }

  // New config → the canonical .gtl/ location. --force overwrites in place,
  // so a legacy repo-root config is never silently shadowed by a .gtl/ one.
  const configPath = existing && options.force
    ? existing
    : await newConfigPath(projectRoot);

  const projectType = await detectProjectType(projectRoot);
  const config = {
    projectType,
    frontendDir: options.frontendDir || 'frontend',
    backendDir: options.backendDir || 'backend',
    srcDir: options.srcDir || 'src',
    appDir: options.appDir || 'app',
  };

  const content = `// gimme-the-lint configuration
// Generated by gimme-the-lint init
module.exports = ${JSON.stringify(config, null, 2)};
`;

  await fs.ensureDir(path.dirname(configPath));
  await fs.writeFile(configPath, content, 'utf8');
  return { created: true, path: configPath, projectType };
}

/**
 * Write an explicit `apps` map into the gimme-the-lint config so the
 * discovered app/linter layout is visible and editable instead of silently
 * re-guessed on every run. Never overwrites an existing config; a new one is
 * written to the canonical .gtl/ location.
 * @param {string} projectRoot
 * @param {{appPath: string, linters: string[]}[]} apps
 */
async function writeAppsConfig(projectRoot, apps) {
  const existing = findConfig(projectRoot);
  if (existing) {
    return { created: false, path: existing };
  }

  const configPath = await newConfigPath(projectRoot);
  const appsObj = {};
  for (const app of apps || []) {
    appsObj[app.appPath] = { linters: app.linters };
  }
  const content = `// gimme-the-lint configuration
// Generated by gimme-the-lint migrate — explicit app/linter bindings.
// Edit this map to correct any mis-discovered apps or linters.
module.exports = ${JSON.stringify({ apps: appsObj }, null, 2)};
`;
  await fs.ensureDir(path.dirname(configPath));
  await fs.writeFile(configPath, content, 'utf8');
  return { created: true, path: configPath, apps: appsObj };
}

module.exports = {
  copyTemplate,
  detectProjectType,
  findConfig,
  getConfig,
  initConfig,
  writeAppsConfig,
  TEMPLATES_DIR,
};
