# Generated by gimme-the-lint — TFLint (recommended tier)
#
# Uses only the bundled "terraform" ruleset, which ships inside the TFLint
# binary. No network access and no `tflint --init` required — works offline.
#
# For deeper, cloud-provider-specific checks (AWS / GCP / Azure best practices),
# add the matching provider plugin block and run `tflint --init` once. Those
# plugins require network access — do NOT add them for air-gapped installs.
#
#   plugin "aws" {
#     enabled = true
#     version = "0.47.0"
#     source  = "github.com/terraform-linters/tflint-ruleset-aws"
#   }

tflint {
  required_version = ">= 0.50"
}

config {
  # "local" evaluates local module calls; "none" skips module evaluation.
  call_module_type = "local"
  # Set true to treat findings as warnings during initial rollout.
  force = false
}

plugin "terraform" {
  enabled = true
  # "recommended" — Terraform-language hygiene. Use "all" for the stricter
  # set (naming conventions, documented variables/outputs, module structure).
  preset = "recommended"
}
